export { DocumentText } from './DocumentText';
export { Search } from './Search';
export { ChevronRight } from './ChevronRight';
export { NewDocument } from './NewDocument';
export { Settings } from './Settings';
export { Login } from './Login';
export { Logout } from './Logout';
export { MoreHorizontal } from './MoreHorizontal';
export { Trash } from './Trash';
export { Restore } from './Restore';
export { Hamburger } from './Hamburger';
export { NextDocs } from './NextDocs';
export { CloseSidebar } from './CloseSidebar';
export { OpenSidebar } from './OpenSidebar';
export { Comments } from './Comments';
export { Globe } from './Globe';
export type { IconProps } from './IconBase';
